version: '3.11'
services:
  app-web-project-name:
    build: .
    container_name: app-web-project-name
    command: npm run serve:web-project-name
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3000:3000
    volumes:
      - .:/code