version: '3.11'
services:
  app-web-project-name:
    build: .
    container_name: app-web-project-name
    command: yarn serve:web-project-name
#    environment:
#      - ID="$UID"
#      - GID="${GID}"
#      - USER="${USER}"
    user: '1001:1001'
    ports:
      - 3000:3000
    volumes:
#      - /etc/passwd:/etc/passwd:ro
#      - /etc/group:/etc/group:ro
      - .:/code
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
      - type: bind
        source: /etc/shadow
        target: /etc/shadow
      - type: bind
        source: /etc/group
        target: /etc/group
